name: dev
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - arrow-cpp=8.0.0=py310h3098874_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boost-cpp=1.73.0=h7f8727e_12
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2024.2.2=hbcca054_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.15.0=py310hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=py310hff52083_0
  - cryptography=37.0.1=py310h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dill=0.3.7=py310h06a4308_0
  - docker-pycreds=0.4.0=py_0
  - einops=0.4.1=pyhd8ed1ab_0
  - entrypoints=0.4=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - future=0.18.3=py310h06a4308_0
  - gflags=2.2.2=he6710b0_0
  - giflib=5.2.1=h7b6447c_0
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.27=pyhd8ed1ab_0
  - glib=2.69.1=h4ff587b_1
  - glog=0.5.0=h2531618_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - grpc-cpp=1.46.1=h33aed49_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py310h06a4308_0
  - ipython=8.4.0=py310h06a4308_0
  - jedi=0.18.1=py310h06a4308_1
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - jupyter_client=7.3.4=py310h06a4308_0
  - jupyter_core=4.10.0=py310h06a4308_0
  - kiwisolver=1.4.2=py310h295c915_0
  - krb5=1.19.4=h568e23c_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - liac-arff=2.5.0=pyhd3eb1b0_1
  - libboost=1.73.0=h28710b8_12
  - libcurl=7.84.0=h91b91d3_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.20.1=h4ff587b_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=12.3.0=h0f45ef3_5
  - libtasn1=4.16.0=h27cfd23_0
  - libthrift=0.15.0=hcc01f38_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.5.1=py310h06a4308_1
  - matplotlib-base=3.5.1=py310ha18d171_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - minio=7.1.0=pyhd3eb1b0_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - numexpr=2.8.3=py310hcea2de6_0
  - numpy-base=1.22.3=py310h9585f30_0
  - openh264=2.1.1=h4ff587b_0
  - openml=0.12.2=pyhd3eb1b0_0
  - openssl=1.1.1w=h7f8727e_0
  - orc=1.7.4=h07ed6aa_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.3=py310h6a678d5_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathtools=0.1.2=py_1
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py310hace64e9_0
  - promise=2.3=py310hff52083_6
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.9.1=py310h5764c6d_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py310h295c915_6
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.4=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py310h06a4308_0
  - pyyaml=6.0=py310h5764c6d_4
  - pyzmq=23.2.0=py310h6a678d5_0
  - qt=5.9.7=h5867ecd_1
  - re2=2022.04.01=h295c915_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.0=py310h06a4308_0
  - scikit-learn=1.1.1=py310h6a678d5_0
  - scipy=1.7.3=py310hfa59a62_0
  - seaborn=0.12.2=py310h06a4308_0
  - sentry-sdk=1.9.0=pyhd8ed1ab_0
  - setproctitle=1.2.3=py310h5764c6d_0
  - shortuuid=1.0.9=pyha770c72_1
  - sip=4.19.13=py310h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.9=h295c915_0
  - sqlite=3.38.5=hc218d9a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py310h7f8727e_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.9=py310h06a4308_0
  - utf8proc=2.6.1=h27cfd23_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xmltodict=0.12.0=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==1.2.0
      - aiohttp==3.8.3
      - aiosignal==1.2.0
      - alabaster==0.7.13
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - avalanche-lib==0.2.1
      - babel==2.12.1
      - backpack-for-pytorch==1.5.2
      - biofluff==3.0.4
      - biopython==1.79
      - biothings-client==0.2.6
      - blinker==1.6.2
      - bokeh==3.0.1
      - cachetools==5.2.0
      - casadi==3.5.6.pre2
      - classicalv1==0.0
      - cloudpickle==2.1.0
      - cmake==3.25.0
      - colorama==0.4.5
      - commonmark==0.9.1
      - configparser==5.3.0
      - contourpy==1.0.6
      - cython==0.29.30
      - datajoint==0.14.1
      - diskcache==5.4.0
      - distlib==0.3.6
      - docutils==0.20.1
      - exceptiongroup==1.0.0
      - fastcore==1.5.27
      - fasteners==0.17.3
      - filelock==3.9.0
      - flask==2.3.2
      - flatbuffers==22.11.23
      - focal-frequency-loss==0.3.0
      - frozenlist==1.3.1
      - fsspec==2022.10.0
      - gast==0.4.0
      - gdown==4.5.1
      - genomepy==0.14.0
      - gimmemotifs==0.17.0
      - glfw==2.5.4
      - google-auth==2.17.3
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - gputil==1.4.0
      - grpcio==1.49.0
      - gym==0.25.0
      - gym-notices==0.0.7
      - h5py==3.7.0
      - higher==0.2.1
      - htseq==2.0.2
      - hydra-core==1.2.0
      - imageio==2.31.1
      - imagesize==1.4.1
      - iniconfig==1.1.1
      - iteround==1.0.4
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - joypy==0.2.6
      - keras==2.12.0
      - lazy-loader==0.2
      - libclang==14.0.6
      - lipstick==0.0.7
      - lit==15.0.7
      - livelossplot==0.5.5
      - llvmlite==0.39.1
      - logomaker==0.8
      - loguru==0.6.0
      - lovely-tensors==0.1.7
      - markdown==3.4.1
      - markupsafe==2.1.2
      - metaworld==0.1.0
      - ml-dtypes==0.1.0
      - mpmath==1.2.1
      - msgpack==1.0.5
      - mujoco==2.2.0
      - mujoco-py==2.1.2.14
      - multidict==6.0.2
      - mygene==3.2.2
      - mysql-connector-python==8.0.31
      - natsort==8.2.0
      - networkx==3.1
      - neuralpredictors==0.3.0
      - nnfabrik==0.2.1
      - norns==0.1.6
      - nose==1.3.7
      - numba==0.56.3
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.1
      - omegaconf==2.2.3
      - opt-einsum==3.3.0
      - otumat==0.3.1
      - palettable==3.3.0
      - patsy==0.5.3
      - pip==23.1.2
      - platformdirs==3.5.1
      - plotly==5.10.0
      - pluggy==1.0.0
      - protobuf==3.20.3
      - pyarrow==9.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pybedtools==0.9.0
      - pybigwig==0.3.18
      - pydeprecate==0.3.2
      - pydot==1.4.2
      - pyfaidx==0.7.1
      - pymysql==1.0.3
      - pyopengl==3.1.7
      - pysam==0.19.1
      - pytest==7.2.0
      - python-graphviz==0.20
      - python-version==0.0.2
      - pytorch-lightning==1.7.7
      - pytorch-sphinx-theme==0.0.19
      - pytorch-triton==2.1.0+2c32f43999
      - pytorchcv==0.0.67
      - pywavelets==1.4.1
      - qnorm==0.8.1
      - quadprog==0.1.11
      - ray==2.4.0
      - recommonmark==0.7.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-image==0.21.0
      - setuptools==59.5.0
      - snowballstemmer==2.2.0
      - sphinx==7.0.1
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - statsmodels==0.13.2
      - sympy==1.11.1
      - tabulate==0.9.0
      - tenacity==8.0.1
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-io-gcs-filesystem==0.28.0
      - termcolor==2.1.1
      - tifffile==2023.4.12
      - tomli==2.0.1
      - torch==2.2.1
      - torchmetrics==0.9.3
      - torchvision==0.17.1
      - torchviz==0.0.2
      - tqdm==4.64.1
      - triton==2.2.0
      - typing-extensions==4.10.0
      - virtualenv==20.21.0
      - wandb==0.16.3
      - watchdog==3.0.0
      - werkzeug==2.3.6
      - wordcloud==1.8.2.2
      - wrapt==1.14.1
      - xdg==5.1.1
      - xgboost==1.6.2
      - xxhash==3.1.0
      - xyzservices==2022.9.0
      - yarl==1.8.1
